name: End-to-end tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: install sercve
        run: npm install -g serve

      - name: Cypress run
        uses: cypress-io/github-action@v1
        with:
          build: yarn run build
          start: serve -s -l 3000 build
          wait-on: http://localhost:3000
